name: 24/7 Real-Time Job Monitor Service

on:
  schedule:
    # Run every 30 minutes for true real-time monitoring
    - cron: '*/30 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  monitor-jobs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run GitHub Job Monitor
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        REED_API_KEY: ${{ secrets.REED_API_KEY }}
        TARGET_EMAIL: kalyogyogi@gmail.com
      run: python github_monitor.py
      
    - name: Commit and push job updates
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "24/7 Job Monitor"
        git add github_monitor_jobs.json *.log
        git diff --staged --quiet || git commit -m "🚀 Real-time job scan update - $(date)"
        git push
